"""Generate synthetic Wind-style Excel/CSV fixtures for V0/V1 engineering tests.

IMPORTANT: everything produced here is SIMULATED data for pipeline validation
only. It must never be presented as real market data or used to draw real
investment conclusions.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from macro_compass import paths  # noqa: E402

N_MONTHS = 36  # well above the required 24 months


def _monthly_index() -> pd.DatetimeIndex:
    end = pd.Timestamp("2026-07-31")
    return pd.date_range(end=end, periods=N_MONTHS, freq="ME")


def _build_series(rng: np.random.Generator) -> dict[str, np.ndarray]:
    t = np.arange(N_MONTHS)

    pmi = 50.0 + 1.2 * np.sin(2 * np.pi * t / 24) + rng.normal(0, 0.4, N_MONTHS)
    cpi = 1.8 + 0.8 * np.sin(2 * np.pi * t / 18 + 1.0) + rng.normal(0, 0.2, N_MONTHS)
    m2 = 8.5 + 0.6 * np.cos(2 * np.pi * t / 30) + rng.normal(0, 0.15, N_MONTHS)
    y10 = 2.4 + 0.35 * np.cos(2 * np.pi * t / 22) + rng.normal(0, 0.05, N_MONTHS)
    spread = 55.0 + 8.0 * np.sin(2 * np.pi * t / 26 + 0.5) + rng.normal(0, 2.0, N_MONTHS)
    usdcny = 7.15 + 0.10 * np.sin(2 * np.pi * t / 28) + rng.normal(0, 0.02, N_MONTHS)
    csi300 = 3900.0 * np.exp(np.cumsum(rng.normal(0.002, 0.03, N_MONTHS)))
    gold = 1950.0 * np.exp(np.cumsum(rng.normal(0.004, 0.02, N_MONTHS)))

    return {
        "PMI": pmi,
        "CPI:同比": cpi,
        "M2:同比": m2,
        "中债国债收益率:10年": y10,
        "信用利差:AA+产业3年": spread,
        "美元兑人民币:中间价": usdcny,
        "沪深300": csi300,
        "黄金现货:SHTAU": gold,
    }


def build_fixture_frame(seed: int = 20260829) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    df = pd.DataFrame({"Date": _monthly_index()})
    for column, values in _build_series(rng).items():
        df[column] = np.round(values, 4)

    # Sprinkle a few missing values and one blank row so the importer's
    # empty/missing handling is exercised end to end.
    df.loc[3, "PMI"] = np.nan
    df.loc[7, "沪深300"] = np.nan
    blank = pd.DataFrame([{col: np.nan for col in df.columns}])
    df = pd.concat([df.iloc[:12], blank, df.iloc[12:]], ignore_index=True)
    return df


def main() -> None:
    paths.FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    df = build_fixture_frame()

    xlsx_path = paths.FIXTURES_DIR / "wind_macro_sample.xlsx"
    csv_path = paths.FIXTURES_DIR / "wind_macro_sample.csv"

    with pd.ExcelWriter(xlsx_path, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name="data", index=False)
        # Machine-readable provenance: this workbook is simulated, not Wind data.
        pd.DataFrame(
            {
                "notice": [
                    "SYNTHETIC TEST DATA - generated by scripts/generate_fixtures.py",
                    "For pipeline engineering validation only. NOT real Wind data.",
                ]
            }
        ).to_excel(writer, sheet_name="README_SYNTHETIC", index=False)

    df.to_csv(csv_path, index=False, encoding="utf-8-sig")

    print(f"Fixture written: {xlsx_path}")
    print(f"Fixture written: {csv_path}")
    print(f"Rows (incl. 1 blank): {len(df)}, series: {len(df.columns) - 1}, months: {N_MONTHS}")
    print("All values are SYNTHETIC - not real market data.")


if __name__ == "__main__":
    main()
